### ISSUE TITLE
eslintにシングルクォート強制を追加

### ISSUE THREAD

**Issue by habutaso** [trisets/trisets#9]
```yaml
rules:
  quotes: ['error', 'single']
```
を追加したいです。`avoidEscape`や`allowTemplateLiterals`はいらないかと思います。
https://eslint.org/docs/latest/rules/quotes

**Comment by terra-d** [comment]
`quotes`ルールは今オフになっていますね（prettierの設定で満足していた・・・）
追加しましょう

```json
    "quotes": [
      0,
      "single",
      `{`
        "avoidEscape": true
      }
    ],
```

`avoidEscape`や`allowTemplateLiterals`については、
`avoidEscape`だけOnにしましょう
こちらは、下のイシューにあるように、変にエスケープを入れてしまって文字列を見づらくしてしまうのを防いでくれるみたいです
https://github.com/eslint/eslint-jp/issues/4

**Comment by habutaso** [comment]
良いですね！
